AllCops:
  Exclude:
    - bin/*
    - Guardfile
    - vendor/**/*
    - db/schema.rb
  TargetRubyVersion: 3.0
  NewCops: enable

Documentation:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - db/**/*
    - spec/**/*
    - test/**/*
    - config/routes.rb

Metrics/ModuleLength:
  CountComments: false

Metrics/ClassLength:
  CountComments: false

Metrics/MethodLength:
  Max: 20
  CountComments: false
  Exclude:
    - db/**/*

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Rails:
  Enabled: true

Layout/CommentIndentation:
  Enabled: false

Layout/LineLength:
  IgnoreCopDirectives: true
  AllowURI: true
  Max: 120
  Exclude:
    - spec/**/*
    - Gemfile

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NumericPredicate:
  AutoCorrect: true

# https://github.com/rubocop-hq/rubocop/issues/1520
Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  AllowInnerSlashes: false
  EnforcedStyle: mixed

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - spec/**/*
    - test/**/*
    - db/schema.rb

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Rails/EnvironmentVariableAccess:
  AllowReads: true